<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>x64</PlatformTarget>
    <VlcWindowsX64Enabled>true</VlcWindowsX64Enabled>
    <VlcWindowsX86Enabled>false</VlcWindowsX86Enabled>
    <VlcWindowsArm64Enabled>false</VlcWindowsArm64Enabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Licenses\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
